# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-darwin = "0ly7pq7lmf9j9av7dcbjcqqgf439yxmvxln5r9ag608i8r66zmzr";
    aarch64-darwin = "0hdrbjz2s347wl5s2aivxblhwx3v683a7p14whi8ki7hg33w4cr6";
  };

  urlMap = {
    x86_64-darwin = "https://github.com/flaticols/gitmd/releases/download/v0.0.3/gitmd_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/flaticols/gitmd/releases/download/v0.0.3/gitmd_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gitmd";
  version = "0.0.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./gitmd $out/bin/gitmd
  '';

  meta = {
    description = "Manage git commit trailers (Reason, Ticket, Assisted, …) for git 2.54+";
    homepage = "https://github.com/flaticols/gitmd";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "x86_64-darwin"
    ];
  };
}
